<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #REQUIRED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT confsetting EMPTY>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster EMPTY>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
		<!ELEMENT device (instance*, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.180 (unknown)" debug="no" mameconfig="10">
	<machine name="wboy" sourcefile="system1.cpp">
		<description>Wonder Boy (set 1, 315-5177)</description>
		<year>1986</year>
		<manufacturer>Escape (Sega license)</manufacturer>
		<rom name="epr-7489.116" size="16384" crc="130f4b70" sha1="4a2ea5bc06f3a240c68813be3a9f9bef2bcf4e9c" region="maincpu" offset="0"/>
		<rom name="epr-7490.109" size="16384" crc="9e656733" sha1="2233beb874b7cb48899afe603fef567932951a88" region="maincpu" offset="4000"/>
		<rom name="epr-7491.96" size="16384" crc="1f7d0efe" sha1="a1b4f8faf1614f4808df1292209c340f1490adbd" region="maincpu" offset="8000"/>
		<rom name="epr-7498.120" size="8192" crc="78ae1e7b" sha1="86032f443359b0bb2766e33024ed2e320aa9bc84" region="soundcpu" offset="0"/>
		<rom name="epr-7497.62" size="8192" crc="08d609ca" sha1="11799e9ef7e6942b304f132b404bff3ed44d524b" region="tiles" offset="0"/>
		<rom name="epr-7496.61" size="8192" crc="6f61fdf1" sha1="21826aebf5835b9f3d9c467c8647809c1bc0d01f" region="tiles" offset="2000"/>
		<rom name="epr-7495.64" size="8192" crc="6a0d2c2d" sha1="8c21d7f0768e8dda2b7185f3c510cae4229a4a2e" region="tiles" offset="4000"/>
		<rom name="epr-7494.63" size="8192" crc="a8e281c7" sha1="a88b80a7b94ab1401bbf28d7707fdf28a5505127" region="tiles" offset="6000"/>
		<rom name="epr-7493.66" size="8192" crc="89305df4" sha1="7a5098624769a31e7512f56831e818bce6a18871" region="tiles" offset="8000"/>
		<rom name="epr-7492.65" size="8192" crc="60f806b1" sha1="f91e5868a455dff2bce3c2891a7cfd648957cd73" region="tiles" offset="a000"/>
		<rom name="epr-7485.117" size="16384" crc="c2891722" sha1="e4e11c0e9bd0dc121c25349493f2b13d2ff8c807" region="sprites" offset="0"/>
		<rom name="epr-7487.04" size="16384" crc="2d3a421b" sha1="d70440a8703ccface3212cd9544c950b36263e8c" region="sprites" offset="4000"/>
		<rom name="epr-7486.110" size="16384" crc="8d622c50" sha1="9a76a50204c618347d3e8eee6cda841becd906eb" region="sprites" offset="8000"/>
		<rom name="epr-7488.05" size="16384" crc="007c2f1b" sha1="c2f1376144a49d20cb35384648e06d06978474c1" region="sprites" offset="c000"/>
		<rom name="pr-5317.76" size="256" crc="648350b8" sha1="c7986aa9127ef5b50b845434cb4e81dff9861cd2" region="proms" offset="0"/>
		<device_ref name="z80_sega2"/>
		<device_ref name="z80"/>
		<device_ref name="timer"/>
		<device_ref name="screen"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="generic_latch_8"/>
		<device_ref name="sn76489a"/>
		<device_ref name="sn76489a"/>
		<device_ref name="z80pio"/>
		<chip type="cpu" tag="maincpu" name="Z80 SegaCrypt2" clock="20000000"/>
		<chip type="cpu" tag="soundcpu" name="Z80" clock="4000000"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="sn1" name="SN76489A" clock="2000000"/>
		<chip type="audio" tag="sn2" name="SN76489A" clock="4000000"/>
		<display tag="screen" type="raster" rotate="0" width="512" height="224" refresh="60.096154" pixclock="10000000" htotal="640" hbend="0" hbstart="512" vtotal="260" vbend="0" vbstart="224" />
		<sound channels="1"/>
		<input players="2" coins="2" service="yes">
			<control type="joy" player="1" buttons="2" ways="2"/>
			<control type="joy" player="2" buttons="2" ways="2"/>
		</input>
		<dipswitch name="Coin A" tag="SWA" mask="15">
			<dipvalue name="4 Coins/1 Credit" value="7"/>
			<dipvalue name="3 Coins/1 Credit" value="8"/>
			<dipvalue name="2 Coins/1 Credit" value="9"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="5"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="4"/>
			<dipvalue name="1 Coin/1 Credit" value="15" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="1"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="2"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="3"/>
			<dipvalue name="2 Coins/3 Credits" value="6"/>
			<dipvalue name="1 Coin/2 Credits" value="14"/>
			<dipvalue name="1 Coin/3 Credits" value="13"/>
			<dipvalue name="1 Coin/4 Credits" value="12"/>
			<dipvalue name="1 Coin/5 Credits" value="11"/>
			<dipvalue name="1 Coin/6 Credits" value="10"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="SWA" mask="240">
			<dipvalue name="4 Coins/1 Credit" value="112"/>
			<dipvalue name="3 Coins/1 Credit" value="128"/>
			<dipvalue name="2 Coins/1 Credit" value="144"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="80"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="64"/>
			<dipvalue name="1 Coin/1 Credit" value="240" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="16"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="32"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="48"/>
			<dipvalue name="2 Coins/3 Credits" value="96"/>
			<dipvalue name="1 Coin/2 Credits" value="224"/>
			<dipvalue name="1 Coin/3 Credits" value="208"/>
			<dipvalue name="1 Coin/4 Credits" value="192"/>
			<dipvalue name="1 Coin/5 Credits" value="176"/>
			<dipvalue name="1 Coin/6 Credits" value="160"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="SWB" mask="1">
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="1"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="SWB" mask="2">
			<dipvalue name="Off" value="2"/>
			<dipvalue name="On" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Lives" tag="SWB" mask="12">
			<dipvalue name="3" value="12" default="yes"/>
			<dipvalue name="4" value="8"/>
			<dipvalue name="5" value="4"/>
			<dipvalue name="Free Play" value="0"/>
		</dipswitch>
		<dipswitch name="Bonus Life" tag="SWB" mask="16">
			<dipvalue name="30k 100k 170k 240k" value="16"/>
			<dipvalue name="30k 120k 210k 300k" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="SWB" mask="32">
			<dipvalue name="No" value="0"/>
			<dipvalue name="Yes" value="32" default="yes"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="SWB" mask="64">
			<dipvalue name="Easy" value="64" default="yes"/>
			<dipvalue name="Hard" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="SWB" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<port tag=":P1">
		</port>
		<port tag=":P2">
		</port>
		<port tag=":SWA">
		</port>
		<port tag=":SWB">
		</port>
		<port tag=":SYSTEM">
		</port>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported"/>
	</machine>
	<machine name="z80_sega2" sourcefile="src/mame/machine/segacrp2_device.cpp" isdevice="yes" runnable="no">
		<description>Z80 SegaCrypt2</description>
	</machine>
	<machine name="z80" sourcefile="src/devices/cpu/z80/z80.cpp" isdevice="yes" runnable="no">
		<description>Z80</description>
	</machine>
	<machine name="timer" sourcefile="src/emu/timer.cpp" isdevice="yes" runnable="no">
		<description>Timer</description>
	</machine>
	<machine name="screen" sourcefile="src/emu/screen.cpp" isdevice="yes" runnable="no">
		<description>Video Screen</description>
	</machine>
	<machine name="gfxdecode" sourcefile="src/emu/drawgfx.cpp" isdevice="yes" runnable="no">
		<description>gfxdecode</description>
	</machine>
	<machine name="palette" sourcefile="src/emu/emupal.cpp" isdevice="yes" runnable="no">
		<description>palette</description>
	</machine>
	<machine name="speaker" sourcefile="src/emu/speaker.cpp" isdevice="yes" runnable="no">
		<description>Speaker</description>
		<sound channels="1"/>
	</machine>
	<machine name="generic_latch_8" sourcefile="src/devices/machine/gen_latch.cpp" isdevice="yes" runnable="no">
		<description>Generic 8-bit latch</description>
	</machine>
	<machine name="sn76489a" sourcefile="src/devices/sound/sn76496.cpp" isdevice="yes" runnable="no">
		<description>SN76489A</description>
		<sound channels="0"/>
	</machine>
	<machine name="z80pio" sourcefile="src/devices/machine/z80pio.cpp" isdevice="yes" runnable="no">
		<description>Z80 PIO</description>
	</machine>
</mame>
